Load messages branch
imoudu13/GuildTalk pull request #88
Opened 2024-03-14 03:12 UTC by GavinAshworth

Implemented message loading upon channel enter. Still need to add username functionality but that will happen when preston implements his work

2024-03-14 04:24 UTC, imoudu13 requested changes
You forgot to test your code as well.

2024-03-14 04:24 UTC, imoudu13 commented on PythonScripts/sendMessage.py
> +    print(messages)
remove print statement

2024-03-14 04:24 UTC, imoudu13 commented on PythonScripts/sendMessage.py
> +    if messages is None:
Remove this if block, there will never be a case when the messages is None

2024-03-15 00:04 UTC, imoudu13 requested changes

2024-03-15 00:06 UTC, GavinAshworth commented on PythonScripts/sendMessageTest.py
> +        mock_channel_info = {"messages": ["Message 1", "Message 2"]}
It just makes it so we dont have to actually get it from the database. Makes the tests run alot faster

2024-03-15 00:08 UTC, merged